import {createClient} from '../../../lib/supabase/server';
import {initialState,providers} from '../../../lib/data';
export const dynamic='force-dynamic';
export async function GET(){try{const supabase=await createClient();const {data:auth,error:authError}=await supabase.auth.getUser();if(authError||!auth.user)return Response.json({error:'Sign in to continue.'},{status:401});const id=auth.user.id;let {data:row,error}=await supabase.from('whosabi_workspaces').select('state,version').eq('user_id',id).maybeSingle();if(error)throw Error('Workspace storage is not ready. Apply supabase/schema.sql to your project.');if(!row){const {error:insertError}=await supabase.from('whosabi_workspaces').insert({user_id:id,state:initialState(),version:0});if(insertError&&insertError.code!=='23505')throw Error('Unable to create your workspace.');const read=await supabase.from('whosabi_workspaces').select('state,version').eq('user_id',id).single();if(read.error)throw Error('Unable to load your workspace.');row=read.data;}return Response.json(row!.state,{headers:{'Cache-Control':'private, no-store'}});}catch(e){console.error(e);return Response.json({error:e instanceof Error?e.message:'Unable to load your workspace.'},{status:503});}}
export async function POST(req:Request){try{const supabase=await createClient();const {data:userData,error:authError}=await supabase.auth.getUser();if(authError||!userData.user)return Response.json({error:'Sign in to continue.'},{status:401});const id=userData.user.id;if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Invalid request'},{status:403});const {data:row,error:readError}=await supabase.from('whosabi_workspaces').select('state,version').eq('user_id',id).single();if(readError)throw Error('Unable to load your workspace.');if(!row)return Response.json({error:'Reload your demo.'},{status:401});const s=row.state;const a=await req.json() as any;const str=(v:any,max=1000)=>typeof v==='string'?v.trim().slice(0,max):'';const property=s.homes.find((p:any)=>p.id===a.property);
switch(a.action){case 'save':if(!property)throw Error('Choose a property');s.saved=s.saved.includes(a.property)?s.saved.filter((v:string)=>v!==a.property):[...s.saved,a.property];break;
case 'review':if(!property||!['property','landlord'].includes(a.target)||!Number.isInteger(a.rating)||a.rating<1||a.rating>5||!str(a.text))throw Error('Complete your review');s.reviews.unshift({id:crypto.randomUUID(),property:a.property,target:a.target,rating:a.rating,text:str(a.text),name:'Demo renter',sample:false});break;
case 'ticket':if(!str(a.title)||!str(a.description))throw Error('Add a title and description');s.tickets.unshift({id:crypto.randomUUID(),property:'p1',title:str(a.title,120),description:str(a.description),category:str(a.category,40),priority:a.priority==='Urgent'?'Urgent':'Normal',status:'Submitted',provider:'',created:new Date().toISOString(),history:[{status:'Submitted',at:new Date().toISOString()}]});break;
case 'status':{const t=s.tickets.find((t:any)=>t.id===a.id);if(!t)throw Error('Ticket not found');const next:any={'Submitted':'Viewed','Viewed':'Assigned','Assigned':'In progress','In progress':'Awaiting confirmation','Awaiting confirmation':'Resolved'};if(a.status!==next[t.status])throw Error('Invalid ticket transition');if(a.status==='Assigned'&&!providers.some(p=>p.name===a.provider))throw Error('Choose a repair provider');t.status=a.status;if(a.provider)t.provider=a.provider;t.history.push({status:a.status,at:new Date().toISOString()});break;}
case 'pay':{const bill=s.bills.find((b:any)=>b.id===a.id);if(!bill)throw Error('Bill not found');if(!bill.paid){bill.paid=true;s.payments.unshift({id:'RC-'+crypto.randomUUID().slice(0,8).toUpperCase(),bill:bill.name,amount:bill.amount,period:bill.period,method:['Demo transfer','Demo card'].includes(a.method)?a.method:'Demo transfer',date:new Date().toISOString(),property:'The Courtyard · Yaba',payer:'Demo renter',landlord:'Mrs. Folake Adebayo'});}break;}
case 'recommend':if(!providers.some(p=>p.id===a.id))throw Error('Provider not found');s.recommendations=s.recommendations.includes(a.id)?s.recommendations.filter((x:string)=>x!==a.id):[...s.recommendations,a.id];break;
case 'property':{const rent=Number(a.rent);const fees=['agency','legal','caution','service'].map(k=>Number(a[k]));if(fees.some(n=>!Number.isFinite(n)||n<0||n>10000000))throw Error('Enter valid fees');if(!str(a.name)||!str(a.address)||!Number.isFinite(rent)||rent<=0||rent>100000000||![1,2,3,4,5].includes(Number(a.beds)))throw Error('Enter valid property details');s.homes.push({id:crypto.randomUUID(),name:str(a.name,100),address:str(a.address,150),area:str(a.area,50),beds:Number(a.beds),rent,agency:fees[0],legal:fees[1],caution:fees[2],service:fees[3],landlord:'Demo landlord',power:'Not reported',water:'Not reported',flood:'Not reported',noise:'Not reported',rating:0,image:'/home-1.jpg',description:'Added in your demo with itemized move-in costs.'});break;}
default:throw Error('Unknown action');}
const {data:updated,error:writeError}=await supabase.from('whosabi_workspaces').update({state:s,version:row.version+1}).eq('user_id',id).eq('version',row.version).select('user_id');if(writeError)throw Error('Unable to save your changes. Please retry.');if(!updated?.length)return Response.json({error:'Another change was saved. Refresh and try again.'},{status:409});return Response.json(s,{headers:{'Cache-Control':'no-store'}});}catch(e){console.error(e);return Response.json({error:e instanceof Error?e.message:'Unable to save. Please retry.'},{status:400});}}
